name: list_item_selector
description: "A Flutter package that provides a customizable dropdown selector with dynamic list of data."
version: 1.0.1
homepage: https://github.com/Fahaddada47/list_item_selector
repository: https://github.com/Fahaddada47/list_item_selector

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

topics:
  - dropdown
  - customization

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

flutter:
  uses-material-design: true
